name: KMP library publish production version

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cocoapods install
        run: (cd sample/ios-app && pod install)
      - name: Publish plugin
        run: ./gradlew -p plugin publishMavenJavaPublicationToOSSRHRepository
      - name: Publish library
        run: ./gradlew publish
